ALTER TABLE clients ADD COLUMN tiktok TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN youtube TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN x TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN telegram TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN threads TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN github TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN behance TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN dribbble TEXT DEFAULT '';
